spring:
  datasource.url: jdbc:mysql://127.0.0.1:3306/score
  datasource.username: root
  datasource.password: root
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
